### ISSUE TITLE
Solving a circuit

### ISSUE THREAD

**Issue by karai17** [SummersEdge23/Circuit-Solver-Web#2]
Hello! Really awesome project you have here! Me and a buddy have been working on a somewhat similar (though distinctly different) project recently and, neither of us being electrical engineers, have been having a pretty tough time finding and desiphering information we've found online.

Our understanding of how electricity... works... is likely lacking in some (all?) areas, but the issue we've found ourselves stuck on for the moment is how to correctly and efficiently solve a circuit so that we know how much current and voltage is at any given spot, at any given time. Our first attempt at this was to build a node tree and trace the circuit backwards from Ground to Vcc to gather all of the components and whatnot that are part of the complete circuit, disgarding those that are not, then propogate the voltage forward. While that works to some degree, it certainly has its issues, one of which being an innacurate model of how voltage and current actual function.

What we have found is that we should be using [Nodal Analysis](https://en.wikipedia.org/wiki/Nodal_analysis#Matrix_form_for_the_node-voltage_equation) to solve the circuit, but we aren't quite sure what that means, exactly. Not being EEs or mathematicians, a lot of the information regarding these ideas tend to be shrouded in language that our feable little programmer minds struggle to comprehend.

If possible, might you be able to explain some of these concepts in, shall we say, plainer English than Wikipedia et al tend to offer? Code or pseudocode examples would also be very welcome, it's just the morse dense mathematical descriptions that we tend to struggle with reading and comprehending.

If you'd like to chat more about EE things in realish time rather than in a GitHub issue thread, let me know and I can add you to Discord or whatever else may work~ We are quite eager to learn more about EE and circuits, we just don't have that mathematical background that allows us to really dive into the material~

**Comment by SummersEdge23** [comment]
Hello! Sorry for the late reply! Interestingly enough that's how I first started looking at the problem of solving circuits as well. I did however go back to Nodal Analysis as well. The issue with nodal analysis is when floating voltage sources get introduced into the circuit. This isn't a complete show stopper but its a bothersome one. https://www.khanacademy.org/science/electrical-engineering/ee-circuit-analysis-topic/ee-dc-circuit-analysis/a/ee-node-voltage-method, this link has the various considerations of nodal analysis. There are two leading methods (from what I know) in order to address this issue. Modified Nodal Analysis which is basically nodal analysis but provides the set of equations to solve for the current in each voltage source. Another method that I've seen is the Sparse Tableau method. I've found more resources on modified nodal analysis as opposed to Sparse Tableau. Modified Nodal Analysis also uses "stamps" or patterns based on the elements nodes to generate a matrix that describes the circuit. The matrix is then solved using various methods. One popular one in LU-Factorization w/ Forward and Backward Substitution. There are various methods including ones for singular matrix (zero's on the diagonal, or rank deficient matrices). One book that can help put all of this into perspective and describe some of the equations / methodology is: https://www.amazon.com/Circuit-Simulation-Farid-N-Najm/dp/0470538716. The book goes through the whole process of formulating the matrices and going through linearization for elements, etc. Hopefully this resource helps!

**Comment by karai17** [comment]
Thank you very much for that information! We'll be sure to check out those resources you provided and might bug you some more if anything specific comes up ;) <3

It's reassuring to hear that you started at about the same place we did and still got to the finish line haha~
